#IMPORT connect_drone_3.script; drone 3 as 0
#DEFINE W #WAIT 100; Every #W is interpreted as #WAIT 100

/lps/set_node_number int 8
#W
/lps/0/set_position float[]    0    0    0
#W
/lps/1/set_position float[] 2.85    0    0
#W
/lps/2/set_position float[] 4.10    0    5
#W
/lps/3/set_position float[] 4.10 4.10    5
#W
/lps/4/set_position float[] 1.75 4.10    0
#W
/lps/5/set_position float[]    0 4.10    5
#W
/lps/6/set_position float[]    0    0    5
#W
/lps/7/set_position float[]    0    0    0
#WAIT 1000
/lps/0/reboot bool 0
#W
/lps/1/reboot bool 0
#W
/lps/2/reboot bool 0
#W
/lps/3/reboot bool 0
#W
/lps/4/reboot bool 0
#W
/lps/5/reboot bool 0
#W
/lps/6/reboot bool 0
#W
/lps/7/reboot bool 0
#W
#UNDEFINE W